name = "BatchedTransformations"
uuid = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
authors = ["Anton Oresten <anton.oresten42@gmail.com> and contributors"]
version = "0.5.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"

[extensions]
ChainRulesCoreExt = "ChainRulesCore"
FunctorsExt = "Functors"

[compat]
ChainRulesCore = "1"
Functors = "0.4"
LinearAlgebra = "1"
MLUtils = "0.4"
NNlib = "0.8, 0.9"
Random = "1"
julia = "1.9"

[extras]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ChainRulesCore", "ChainRulesTestUtils", "Functors"]
